/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ldts.terrarialike;

import ldts.terrarialike.GUI.GUILanterna;
import ldts.terrarialike.controller.GameController;
import ldts.terrarialike.model.World;
import ldts.terrarialike.view.GameView;

public class App {

    public static void main(String[] args) throws InterruptedException{
        World world = new World();
        GameController cGameController = new GameController();
        GUILanterna gLanterna = new GUILanterna(200,100, "TerrariaLike");
        GameView gView = new GameView(gLanterna, world);

        Thread.sleep(1000*10);
    }
}
