/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ldts.terrarialike;

public class App {
    public static void main(String[] args) {
        System.out.println("Pog");
    }
}
